name: Run Python Tests

on: [push, pull_request]

jobs:
    setup:
        name: Setup and run python tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.10"
            - name: Install dependecies
              run: |
                  sudo apt update && sudo apt install portaudio19-dev espeak ffmpeg libespeak1
                  pip install -r requirements.txt
    test:
        name: Run Tests
        runs-on: ubuntu-latest
        needs: setup
        steps:
            - name: Run test with pytest
              run: coverage run -m pytest
    report:
        name: Generate coverage report
        runs-on: ubuntu-latest
        needs: [setup, test]
        permissions:
            pull-requests: write
            contents: read
        steps:
            - name: Print results
              run: coverage report
            - name: Generate xml report
              run: coverage xml
            - name: Print coverage to pull request
              uses: orgoro/coverage@v3
              with:
                  coverageFile: coverage.xml
                  token: ${{ secrets.GITHUB_TOKEN }}
                  thresholdAll: 0.8
              if: github.event_name == 'pull_request'
