name: Run Python Tests

on: [push, pull_request]

jobs:
    test:
        name: Setup and run python tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.10"
            - name: Install dependecies
              run: |
                  apt install portaudio19-dev
                  pip install -r requirements.txt
            - name: Run test with pytest
              run: python -m pytest
